name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
        id: go

      - uses: actions/checkout@v4

      - name: Build
        run: |
          go build -v ./...
          cd kubernetes
          go build -v ./...

      - name: Test
        run: |
          go test -v ./...
          cd kubernetes
          go test -v ./...
